import profile from '@/data/githubProfile.json';

/**
 * Display helpers for the GitHub timeline window. The dataset is a committed
 * snapshot regenerated by scripts/fetchGithubProfile.mjs (which owns the
 * counting rules and the public-repos-only guarantee); this module only
 * shapes it for templates.
 */

export type GithubRepo = {
  repo: string;
  stars: number;
  prs: number;
  domain: string;
};

export type GithubYear = {
  year: number;
  prs: number;
  commits: number;
  reviews: number;
  months: number[];
  domains: { domain: string; prs: number }[];
  repos: GithubRepo[];
};

export type GithubProfile = {
  generatedAt: string;
  login: string;
  totals: { prs: number; repos: number; years: number };
  years: GithubYear[];
};

export const githubProfile = profile as GithubProfile;

/** How many repos a year shows before the expandable "+n more". */
export const GH_TOP_REPOS = 10;

/**
 * Domain colors follow the blog's branch-tag vocabulary (BRANCH_COLORS),
 * except tooling: #a8443a reads identical to react's #9a4f00 at pill-dot
 * size, so it shifts to a colder crimson here.
 */
export const GH_DOMAIN_COLORS: Record<string, string> = {
  react: '#9a4f00',
  testing: '#3b6db8',
  graphql: '#3b8a9e',
  tooling: '#a12a4a',
  typescript: '#4a7c3a',
  other: '#7a7160',
};

export const ghDomainColor = (domain: string): string =>
  GH_DOMAIN_COLORS[domain] ?? GH_DOMAIN_COLORS.other;

export const ghAccentColor = (year: GithubYear): string =>
  ghDomainColor(year.domains[0]?.domain ?? 'other');

export const formatStars = (stars: number): string =>
  stars >= 1000
    ? `${(stars / 1000).toFixed(stars >= 10000 ? 0 : 1)}k`
    : String(stars);

/** 12-char monthly activity sparkline (5 intensity levels). */
export function monthSparkline(months: number[]): string {
  const max = Math.max(...months, 1);
  const BLOCKS = ['·', '▁', '▂', '▅', '█'];
  return months
    .map((count) => {
      if (count === 0) return BLOCKS[0];
      const t = count / max;
      return BLOCKS[t > 0.75 ? 4 : t > 0.5 ? 3 : t > 0.25 ? 2 : 1];
    })
    .join('');
}

export const ghPullsUrl = (repo: string): string =>
  `https://github.com/${repo}/pulls?q=${encodeURIComponent(`is:pr author:${githubProfile.login}`)}`;
